import { ReactNode } from 'react'
import './globals.css'
import { Baloo_Bhai_2 } from 'next/font/google'

const baloo_behai_2 = Baloo_Bhai_2({
  variable: '--baloo-font',
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${baloo_behai_2.variable} font-baloo`}>
      <body>{children}</body>
    </html>
  )
}
